import React, { Children } from "react";
import Heading from "../elements/Heading";
import Text from "../elements/Text";
import Layout from "../Layout/Layout";

function Privacy() {
  return (
    <Layout title={"Cookie-policy - gluestack"}>
      <div className="container py-14">
        <Heading priority={1}>Privacy Policy </Heading>
        <div className="py-16">
          <ol className="list-decimal list-outside	">
            <li>
              <span className="text-md font-displaySemibold">Introduction</span>
              <Text style="py-4">
                <p>
                  Welcome to{" "}
                  <span className="font-displaySemibold">GeekyAnts Inc.</span>{" "}
                </p>
                <p className="py-4">
                  GeekyAnts Inc. (“us”, “we”, or “our”) operates{" "}
                  <a href="https://gluestack.io/" className="text-primary">
                    https://gluestack.io/
                  </a>
                  , and/or{" "}
                  <a href="https://seal.gluestack.io/" className="text-primary">
                    https://seal.gluestack.io/{" "}
                  </a>
                  (hereinafter referred to as each a “Site”).
                </p>
                <p className="py-4">
                  Our Privacy Policy governs your visit to{" "}
                  <a href="https://gluestack.io/" className="text-primary">
                    https://gluestack.io/
                  </a>
                  , and/or{" "}
                  <a href="https://seal.gluestack.io/" className="text-primary">
                    https://seal.gluestack.io/{" "}
                  </a>{" "}
                  and the use of our Service as defined hereunder, and explains
                  how we collect, safeguard and disclose information that
                  results from your use of our Service.
                </p>
                <p className="py-4">
                  We use and/or collect your personal data and other information
                  to provide and improve our Service. By using our Sites and
                  Services, you agree to the collection and use of information
                  in accordance with this policy. Therefore, we recommend that
                  you read this Privacy Policy carefully as it provides
                  important information about your personal data and your rights
                  under the law. Unless otherwise defined in this Privacy
                  Policy, the terms used in this Privacy Policy have the same
                  meanings as in our Terms of Service.
                </p>
                <p className="py-4 font-displaySemibold">
                  Our Terms of Service (“Terms”) govern all use of our Service
                  and together with the Privacy Policy constitute your agreement
                  with us (“Agreement”).
                </p>
              </Text>
            </li>

            <li>
              <span className="text-md font-displaySemibold">Definitions</span>
              <Text style="py-4">
                <p>
                  <span className="font-displaySemibold">SERVICE</span> means{" "}
                  <a href="https://gluestack.io/" className="text-primary">
                    https://gluestack.io/
                  </a>
                  , and/or{" "}
                  <a href="https://seal.gluestack.io/" className="text-primary">
                    https://seal.gluestack.io/{" "}
                  </a>{" "}
                  website operated by GeekyAnts Inc. https://gluestack.io/ is a
                  open source full-stack framework for web, mobile and backend.
                  https://seal.gluestack.io/ provides a cloud platform for
                  deployment, hosting, sharing services and related analytics
                  tools. .
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">
                    PERSONAL DATA OR PERSONAL INFORMATION{" "}
                  </span>
                  means data that is unique to a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">USAGE DATA </span>is
                  data collected automatically either generated by the use of
                  the Service or from the Service infrastructure itself (for
                  example, the duration of a page visit).
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">COOKIES </span>are
                  small files stored on your device (computer or mobile device).
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">DATA CONTROLLER </span>
                  means a natural or legal person who (either alone or jointly
                  or in common with other persons) determines the purposes for
                  which and the manner in which any personal data are, or are to
                  be, processed. For the purpose of this Privacy Policy, we are
                  a Data Controller when we process your data.
                </p>

                <p className="py-4">
                  <span className="font-displaySemibold">DATA CONTROLLER </span>
                  means a natural or legal person who (either alone or jointly
                  or in common with other persons) determines the purposes for
                  which and the manner in which any personal data are, or are to
                  be, processed. For the purpose of this Privacy Policy, we are
                  a Data Controller when we process your data.
                </p>

                <p className="py-4">
                  <span className="font-displaySemibold">
                    DATA PROCESSORS (OR SERVICE PROVIDERS){" "}
                  </span>
                  means any natural or legal person who processes the data on
                  behalf of the Data Controller. We may use the services of
                  various Service Providers in order to process your data more
                  effectively.
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">DATA SUBJECT </span>is
                  any living individual who is the subject of Personal Data.
                </p>

                <p className="py-4">
                  <span className="font-displaySemibold">THE USER </span>is the
                  individual using our Service. The User corresponds to the Data
                  Subject, who is the subject of Personal Data.
                </p>

                <p className="py-4">
                  <span className="font-displaySemibold">CUSTOMERS</span>, this
                  includes any individual who uses our Service individually or
                  on behalf of an entity or organization.
                </p>
                <p className="py-4">
                  <span className="font-displaySemibold">END USER</span>, As
                  part of our Services, we also provide hosting solutions to our
                  Customers through our global servers. Our customers may
                  collect personal data from the Customer’s End Users in
                  connection with the products or services that they offer. For
                  the purpose of this Privacy Policy, such Customer’s End Users’
                  are hereinafter termed as End User.
                </p>
              </Text>
            </li>

            <li>
              <span className="text-md font-displaySemibold">
                Information Collection and Use
              </span>
              <Text style="py-4">
                <p>
                  When you use our Services, we collect several different types
                  of information as defined below for various purposes to
                  provide and improve our Service to you.
                </p>
              </Text>
            </li>

            <li>
              <span className="text-md font-displaySemibold">
                Types of Data Collected
              </span>
              <Text style="py-4">
                <ul className="list-disc list-outside">
                  <li>
                    <span className="font-displaySemibold">Personal Data</span>
                    <p className="py-4">
                      While using our Service, we may ask you to provide us with
                      certain personally identifiable information that can be
                      used to contact or identify you (“Personal Data”).
                      Personally identifiable information may include, but is
                      not limited to:
                      <p>(a) Email address</p>
                      <p>(b) First name and last name</p>
                      <p>(c) Phone number</p>
                      <p>(d) Address, State, Province, ZIP/Postal code, City</p>
                      <p>(e) Cookies and Usage Data</p>
                      <p>(e) Cookies and Usage Data</p>
                      <p className="py-4">
                        We may use your Personal Data to contact you with
                        newsletters, marketing or promotional materials and
                        other information that may be of interest to you. You
                        may opt-out of receiving any, or all, of these
                        communications from us by emailing at{" "}
                        <a
                          href="mailto:hello@gluestack.io"
                          className="text-primary"
                        >
                          hello@gluestack.io
                        </a>
                        .
                      </p>
                    </p>
                  </li>
                  <li>
                    <span className="font-displaySemibold">Usage Data</span>
                    <p className="py-4">
                      We may also collect information that your browser sends
                      whenever you visit our Service or when you access the
                      Service by or through a mobile device (“Usage Data”).
                    </p>
                    <p className="py-4">
                      This Usage Data may include information such as your
                      computer's Internet Protocol address (e.g. IP address),
                      browser type, browser version, the pages of our Service
                      that you visit, the time and date of your visit, the time
                      spent on those pages, unique device identifiers and other
                      diagnostic data.
                    </p>
                    <p className="py-4">
                      When you access Service with a mobile device, this Usage
                      Data may include information such as the type of mobile
                      device you use, your mobile device unique ID, the IP
                      address of your mobile device, your mobile operating
                      system, the type of mobile Internet browser you use,
                      unique device identifiers and other diagnostic data.
                    </p>
                  </li>
                  <li>
                    <span className="font-displaySemibold">Location Data</span>
                    <p className="py-4">
                      We may use and store information about your location if
                      you give us permission to do so (“Location Data”). We use
                      this data to provide features of our Service, to improve
                      and customize our Service.
                    </p>
                    <p className="py-4">
                      You can enable or disable location services when you use
                      our Service at any time by way of your device settings.
                    </p>
                  </li>
                  <li>
                    <span className="font-displaySemibold">
                      Tracking Cookies Data
                    </span>
                    <p className="py-4">
                      We use cookies and similar tracking technologies to track
                      the activity on our Service and we hold certain
                      information.
                    </p>
                    <p className="py-4">
                      Cookies are files with a small amount of data which may
                      include an anonymous unique identifier. Cookies are sent
                      to your browser from a website and stored on your device.
                      Other tracking technologies are also used such as beacons,
                      tags and scripts to collect and track information and to
                      improve and analyze our Service.
                    </p>
                    <p className="py-4">
                      You can instruct your browser to refuse all cookies or to
                      indicate when a cookie is being sent. However, if you do
                      not accept cookies, you may not be able to use some
                      portions of our Service.
                    </p>
                    <p className="py-4">
                      Examples of Cookies we use:
                      <br />
                      (a) Session Cookies: We use Session Cookies to operate our
                      Service.
                      <br />
                      (b) Preference Cookies: We use Preference Cookies to
                      remember your preferences and various settings.
                      <br />
                      (c) Security Cookies: We use Security Cookies for security
                      purposes.
                      <br />
                      (d) Advertising Cookies: Advertising Cookies are used to
                      serve you with advertisements that may be relevant to you
                      and your interests.
                      <br />
                      For more information on our use of cookies and the data
                      that they collect, see our Cookie Policy.
                    </p>
                  </li>
                  <li>
                    <span className="font-displaySemibold">Other Data</span>
                    <p className="py-4">
                      While using our Service, we may also collect the following
                      information: sex, age, date of birth, place of birth,
                      passport details, citizenship, registration at the place
                      of residence and actual address, telephone number (work,
                      mobile), details of documents on education, qualification,
                      professional training, employment agreements,
                      non-disclosure agreements, information on bonuses and
                      compensation, information on marital status, family
                      members, social security (or other taxpayer
                      identification) number, office location, and other data.
                    </p>
                  </li>
                </ul>
              </Text>
            </li>

            <li>
              <span className="text-md font-displaySemibold">Use of Data</span>
              <Text style="py-4"></Text>
            </li>
          </ol>
        </div>
      </div>
    </Layout>
  );
}

export default Privacy;
